### PR TITLE
Fix plurality for numbers more than 100.

### PR DESCRIPTION
**Pull request by alexlcdee**
Example of failing test:

```php
assertEquals('домов', Plurality::pluralize('дом', 213)); // returns 'дома'
```

Fix: added recursive call of Plurality::getNumeralForm if $count > 100 with $count % 100.

### CODE REVIEW

**Comment by wapmorgan** [comment]
Ok, thanks for PR, but I can't accept it due to changes in code style: spaces instead of tabs, opening brace on the next line, spaces around `.` in string concatenations.
Please, fix these problems and I'd be happy to merge it.
And also it'd better be
```php
if ($count > 100) $count %= 100;
```
Why we need another call?

**Comment by alexlcdee** [comment]
Fixed.
Of course we don't need another call, simply I don't thought about it.

**Comment by wapmorgan** [comment]
Thanks for PR!

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

A> Example of failing test:
A>  assertEquals('домов', Plurality::pluralize('дом', 213)); //returns 'дома'
A>  Fix: added recursive call of Plurality::getNumeralForm if $count > 100 with $count % 100.

A> You can view, comment on, or merge this pull request online at:
A>    https://github.com/wapmorgan/Morphos/pull/5
A> Commit Summary
A>  Fix plurality for numbers more than 100. Add recursive call of
A> Plurality::getNumeralForm with count divided by 100 
A> File Changes
A>  Msrc/Russian/Plurality.php(307) 
A> Mtests/Russian/PluralityTest.php(40)   
A> Patch Links:
A> 
A> https://github.com/wapmorgan/Morphos/pull/5.patchhttps://github.com/wapmorgan/Morphos/pull/5.diff
A> —
A> You are receiving this because you are subscribed to this thread.
A> Reply to this email directly, view it on GitHub, or mute the thread.
A>   
A>     
A> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wapmorgan/Morphos","title":"wapmorgan/Morphos","subtitle":"GitHub
A> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
A> in
A> GitHub","url":"https://github.com/wapmorgan/Morphos"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Fix
A> plurality for numbers more than 100. (#5)"}],"action":{"name":"View
A> Pull Request","url":"https://github.com/wapmorgan/Morphos/pull/5"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

S> Ok, thanks for PR, but I can't accept it due to changes in code
S> style: spaces instead of tabs, opening brace on the next line,
S> spaces around .in string concatenations.
S> Please, fix these problems and I'd be happy to merge it.
S> And also it'd better be
S>  if($count > 100) $count %= 100;
S>  Why we need another call?
S> —
S> You are receiving this because you are subscribed to this thread.
S> Reply to this email directly, view it on GitHub, or mute the thread.
S>   
S>     
S> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wapmorgan/Morphos","title":"wapmorgan/Morphos","subtitle":"GitHub
S> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
S> in
S> GitHub","url":"https://github.com/wapmorgan/Morphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wapmorgan
S> in #5: Ok, thanks for PR, but I can't accept it due to changes in
S> code style: spaces instead of tabs, opening brace on the next line,
S> spaces around `.` in string concatenations.\r\nPlease, fix these
S> problems and I'd be happy to merge it.\r\nAnd also it'd better
S> be\r\n```php\r\nif ($count \u003e 100) $count %= 100;\r\n```\r\nWhy
S> we need another call?"}],"action":{"name":"View Pull
S> Request","url":"https://github.com/wapmorgan/Morphos/pull/5#issuecomment-308109095"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Pull request merged**
